name: Auto Build Test

on:
  push:
    branches: [ "bepinex5" ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    
    # Build the project
    - name: Build HsMod
      run: dotnet build --configuration Release --no-restore
- name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HsMod-Release-Build  # 这是最终生成压缩包的名字，你可以随便改
        path: ./**/bin/Release/    # 抓取所有 bin/Release 文件夹下的产物
